"""
CPU
"""

from cpu.register import Register
import cpu.op


class CPU:
    def __init__(self):
        self.register = Register()
        self.cartridge_data = None

        self.prefix_cb = False
        self.halted = False  # for 76 (HALT)
        self.stopped = False  # for 10 (STOP)
        self.interrupts_enabled = False  # for F3 (DI) and FB (EI)
        self.disable_interrupts_requested = False  # for F3 (DI) and FB (EI)

    def execute(self, cartridge_data):
        self.cartridge_data = cartridge_data

        while(True):
            opcode = self._read_next_byte_from_cartridge()
            if self.prefix_cb:
                instruction = _instruction_cb_dict[opcode]
            else:
                instruction = _instruction_dict[opcode]

            if instruction["extra_bytes"] > 0:
                params = []
                for i in range(0,instruction["extra_bytes"]):
                    params.append(self._read_next_byte_from_cartridge())
                print("Executing","{:02X}".format(opcode),"with params",params)
                instruction["execute"](self,params)
            else:
                print("Executing", "{:02X} ".format(opcode))
                instruction["execute"](self)

    def _read_next_byte_from_cartridge(self):
        """
        Read the next data from the ROM, increment Program Counter
        :return: 8-bit data read from ROM
        """
        data = self.cartridge_data[self.register.PC]
        self.register.PC += 1
        return data


_instruction_dict = {
    0x00: {"execute": cpu.op.code_00, "extra_bytes": 0},
    0x01: {"execute": cpu.op.code_01, "extra_bytes": 2},
    0x02: {"execute": cpu.op.code_02, "extra_bytes": 0},
    0x03: {"execute": cpu.op.code_03, "extra_bytes": 0},
    0x04: {"execute": cpu.op.code_04, "extra_bytes": 0},
    0x05: {"execute": cpu.op.code_05, "extra_bytes": 0},
    0x06: {"execute": cpu.op.code_06, "extra_bytes": 1},
    0x07: {"execute": cpu.op.code_07, "extra_bytes": 0},
    0x08: {"execute": cpu.op.code_08, "extra_bytes": 2},
    0x09: {"execute": cpu.op.code_09, "extra_bytes": 0},
    0x0a: {"execute": cpu.op.code_0a, "extra_bytes": 0},
    0x0b: {"execute": cpu.op.code_0b, "extra_bytes": 0},
    0x0c: {"execute": cpu.op.code_0c, "extra_bytes": 0},
    0x0d: {"execute": cpu.op.code_0d, "extra_bytes": 0},
    0x0e: {"execute": cpu.op.code_0e, "extra_bytes": 1},
    0x0f: {"execute": cpu.op.code_0f, "extra_bytes": 0},

    0x10: {"execute": cpu.op.code_10, "extra_bytes": 1},
    0x11: {"execute": cpu.op.code_11, "extra_bytes": 2},
    0x12: {"execute": cpu.op.code_12, "extra_bytes": 0},
    0x13: {"execute": cpu.op.code_13, "extra_bytes": 0},
    0x14: {"execute": cpu.op.code_14, "extra_bytes": 0},
    0x15: {"execute": cpu.op.code_15, "extra_bytes": 0},
    0x16: {"execute": cpu.op.code_16, "extra_bytes": 1},
    0x17: {"execute": cpu.op.code_17, "extra_bytes": 0},
    0x18: {"execute": cpu.op.code_18, "extra_bytes": 1},
    0x19: {"execute": cpu.op.code_19, "extra_bytes": 0},
    0x1a: {"execute": cpu.op.code_1a, "extra_bytes": 0},
    0x1b: {"execute": cpu.op.code_1b, "extra_bytes": 0},
    0x1c: {"execute": cpu.op.code_1c, "extra_bytes": 0},
    0x1d: {"execute": cpu.op.code_1d, "extra_bytes": 0},
    0x1e: {"execute": cpu.op.code_1e, "extra_bytes": 1},
    0x1f: {"execute": cpu.op.code_1f, "extra_bytes": 0},

    0x20: {"execute": cpu.op.code_20, "extra_bytes": 1},
    0x21: {"execute": cpu.op.code_21, "extra_bytes": 2},
    0x22: {"execute": cpu.op.code_22, "extra_bytes": 0},
    0x23: {"execute": cpu.op.code_23, "extra_bytes": 0},
    0x24: {"execute": cpu.op.code_24, "extra_bytes": 0},
    0x25: {"execute": cpu.op.code_25, "extra_bytes": 0},
    0x26: {"execute": cpu.op.code_26, "extra_bytes": 1},
    0x27: {"execute": cpu.op.code_27, "extra_bytes": 0},
    0x28: {"execute": cpu.op.code_28, "extra_bytes": 1},
    0x29: {"execute": cpu.op.code_29, "extra_bytes": 0},
    0x2a: {"execute": cpu.op.code_2a, "extra_bytes": 0},
    0x2b: {"execute": cpu.op.code_2b, "extra_bytes": 0},
    0x2c: {"execute": cpu.op.code_2c, "extra_bytes": 0},
    0x2d: {"execute": cpu.op.code_2d, "extra_bytes": 0},
    0x2e: {"execute": cpu.op.code_2e, "extra_bytes": 1},
    0x2f: {"execute": cpu.op.code_2f, "extra_bytes": 0},

    0x30: {"execute": cpu.op.code_30, "extra_bytes": 1},
    0x31: {"execute": cpu.op.code_31, "extra_bytes": 2},
    0x32: {"execute": cpu.op.code_32, "extra_bytes": 0},
    0x33: {"execute": cpu.op.code_33, "extra_bytes": 0},
    0x34: {"execute": cpu.op.code_34, "extra_bytes": 0},
    0x35: {"execute": cpu.op.code_35, "extra_bytes": 0},
    0x36: {"execute": cpu.op.code_36, "extra_bytes": 1},
    0x37: {"execute": cpu.op.code_37, "extra_bytes": 0},
    0x38: {"execute": cpu.op.code_38, "extra_bytes": 1},
    0x39: {"execute": cpu.op.code_39, "extra_bytes": 0},
    0x3a: {"execute": cpu.op.code_3a, "extra_bytes": 0},
    0x3b: {"execute": cpu.op.code_3b, "extra_bytes": 0},
    0x3c: {"execute": cpu.op.code_3c, "extra_bytes": 0},
    0x3d: {"execute": cpu.op.code_3d, "extra_bytes": 0},
    0x3e: {"execute": cpu.op.code_3e, "extra_bytes": 1},
    0x3f: {"execute": cpu.op.code_3f, "extra_bytes": 0},

    0x40: {"execute": cpu.op.code_40, "extra_bytes": 0},
    0x41: {"execute": cpu.op.code_41, "extra_bytes": 0},
    0x42: {"execute": cpu.op.code_42, "extra_bytes": 0},
    0x43: {"execute": cpu.op.code_43, "extra_bytes": 0},
    0x44: {"execute": cpu.op.code_44, "extra_bytes": 0},
    0x45: {"execute": cpu.op.code_45, "extra_bytes": 0},
    0x46: {"execute": cpu.op.code_46, "extra_bytes": 0},
    0x47: {"execute": cpu.op.code_47, "extra_bytes": 0},
    0x48: {"execute": cpu.op.code_48, "extra_bytes": 0},
    0x49: {"execute": cpu.op.code_49, "extra_bytes": 0},
    0x4a: {"execute": cpu.op.code_4a, "extra_bytes": 0},
    0x4b: {"execute": cpu.op.code_4b, "extra_bytes": 0},
    0x4c: {"execute": cpu.op.code_4c, "extra_bytes": 0},
    0x4d: {"execute": cpu.op.code_4d, "extra_bytes": 0},
    0x4e: {"execute": cpu.op.code_4e, "extra_bytes": 0},
    0x4f: {"execute": cpu.op.code_4f, "extra_bytes": 0},

    0x50: {"execute": cpu.op.code_50, "extra_bytes": 0},
    0x51: {"execute": cpu.op.code_51, "extra_bytes": 0},
    0x52: {"execute": cpu.op.code_52, "extra_bytes": 0},
    0x53: {"execute": cpu.op.code_53, "extra_bytes": 0},
    0x54: {"execute": cpu.op.code_54, "extra_bytes": 0},
    0x55: {"execute": cpu.op.code_55, "extra_bytes": 0},
    0x56: {"execute": cpu.op.code_56, "extra_bytes": 0},
    0x57: {"execute": cpu.op.code_57, "extra_bytes": 0},
    0x58: {"execute": cpu.op.code_58, "extra_bytes": 0},
    0x59: {"execute": cpu.op.code_59, "extra_bytes": 0},
    0x5a: {"execute": cpu.op.code_5a, "extra_bytes": 0},
    0x5b: {"execute": cpu.op.code_5b, "extra_bytes": 0},
    0x5c: {"execute": cpu.op.code_5c, "extra_bytes": 0},
    0x5d: {"execute": cpu.op.code_5d, "extra_bytes": 0},
    0x5e: {"execute": cpu.op.code_5e, "extra_bytes": 0},
    0x5f: {"execute": cpu.op.code_5f, "extra_bytes": 0},

    0x60: {"execute": cpu.op.code_60, "extra_bytes": 0},
    0x61: {"execute": cpu.op.code_61, "extra_bytes": 0},
    0x62: {"execute": cpu.op.code_62, "extra_bytes": 0},
    0x63: {"execute": cpu.op.code_63, "extra_bytes": 0},
    0x64: {"execute": cpu.op.code_64, "extra_bytes": 0},
    0x65: {"execute": cpu.op.code_65, "extra_bytes": 0},
    0x66: {"execute": cpu.op.code_66, "extra_bytes": 0},
    0x67: {"execute": cpu.op.code_67, "extra_bytes": 0},
    0x68: {"execute": cpu.op.code_68, "extra_bytes": 0},
    0x69: {"execute": cpu.op.code_69, "extra_bytes": 0},
    0x6a: {"execute": cpu.op.code_6a, "extra_bytes": 0},
    0x6b: {"execute": cpu.op.code_6b, "extra_bytes": 0},
    0x6c: {"execute": cpu.op.code_6c, "extra_bytes": 0},
    0x6d: {"execute": cpu.op.code_6d, "extra_bytes": 0},
    0x6e: {"execute": cpu.op.code_6e, "extra_bytes": 0},
    0x6f: {"execute": cpu.op.code_6f, "extra_bytes": 0},

    0x70: {"execute": cpu.op.code_70, "extra_bytes": 0},
    0x71: {"execute": cpu.op.code_71, "extra_bytes": 0},
    0x72: {"execute": cpu.op.code_72, "extra_bytes": 0},
    0x73: {"execute": cpu.op.code_73, "extra_bytes": 0},
    0x74: {"execute": cpu.op.code_74, "extra_bytes": 0},
    0x75: {"execute": cpu.op.code_75, "extra_bytes": 0},
    0x76: {"execute": cpu.op.code_76, "extra_bytes": 0},
    0x77: {"execute": cpu.op.code_77, "extra_bytes": 0},
    0x78: {"execute": cpu.op.code_78, "extra_bytes": 0},
    0x79: {"execute": cpu.op.code_79, "extra_bytes": 0},
    0x7a: {"execute": cpu.op.code_7a, "extra_bytes": 0},
    0x7b: {"execute": cpu.op.code_7b, "extra_bytes": 0},
    0x7c: {"execute": cpu.op.code_7c, "extra_bytes": 0},
    0x7d: {"execute": cpu.op.code_7d, "extra_bytes": 0},
    0x7e: {"execute": cpu.op.code_7e, "extra_bytes": 0},
    0x7f: {"execute": cpu.op.code_7f, "extra_bytes": 0},

    0x80: {"execute": cpu.op.code_80, "extra_bytes": 0},
    0x81: {"execute": cpu.op.code_81, "extra_bytes": 0},
    0x82: {"execute": cpu.op.code_82, "extra_bytes": 0},
    0x83: {"execute": cpu.op.code_83, "extra_bytes": 0},
    0x84: {"execute": cpu.op.code_84, "extra_bytes": 0},
    0x85: {"execute": cpu.op.code_85, "extra_bytes": 0},
    0x86: {"execute": cpu.op.code_86, "extra_bytes": 0},
    0x87: {"execute": cpu.op.code_87, "extra_bytes": 0},
    0x88: {"execute": cpu.op.code_88, "extra_bytes": 0},
    0x89: {"execute": cpu.op.code_89, "extra_bytes": 0},
    0x8a: {"execute": cpu.op.code_8a, "extra_bytes": 0},
    0x8b: {"execute": cpu.op.code_8b, "extra_bytes": 0},
    0x8c: {"execute": cpu.op.code_8c, "extra_bytes": 0},
    0x8d: {"execute": cpu.op.code_8d, "extra_bytes": 0},
    0x8e: {"execute": cpu.op.code_8e, "extra_bytes": 0},
    0x8f: {"execute": cpu.op.code_8f, "extra_bytes": 0},

    0x90: {"execute": cpu.op.code_90, "extra_bytes": 0},
    0x91: {"execute": cpu.op.code_91, "extra_bytes": 0},
    0x92: {"execute": cpu.op.code_92, "extra_bytes": 0},
    0x93: {"execute": cpu.op.code_93, "extra_bytes": 0},
    0x94: {"execute": cpu.op.code_94, "extra_bytes": 0},
    0x95: {"execute": cpu.op.code_95, "extra_bytes": 0},
    0x96: {"execute": cpu.op.code_96, "extra_bytes": 0},
    0x97: {"execute": cpu.op.code_97, "extra_bytes": 0},
    0x98: {"execute": cpu.op.code_98, "extra_bytes": 0},
    0x99: {"execute": cpu.op.code_99, "extra_bytes": 0},
    0x9a: {"execute": cpu.op.code_9a, "extra_bytes": 0},
    0x9b: {"execute": cpu.op.code_9b, "extra_bytes": 0},
    0x9c: {"execute": cpu.op.code_9c, "extra_bytes": 0},
    0x9d: {"execute": cpu.op.code_9d, "extra_bytes": 0},
    0x9e: {"execute": cpu.op.code_9e, "extra_bytes": 0},
    0x9f: {"execute": cpu.op.code_9f, "extra_bytes": 0},

    0xa0: {"execute": cpu.op.code_a0, "extra_bytes": 0},
    0xa1: {"execute": cpu.op.code_a1, "extra_bytes": 0},
    0xa2: {"execute": cpu.op.code_a2, "extra_bytes": 0},
    0xa3: {"execute": cpu.op.code_a3, "extra_bytes": 0},
    0xa4: {"execute": cpu.op.code_a4, "extra_bytes": 0},
    0xa5: {"execute": cpu.op.code_a5, "extra_bytes": 0},
    0xa6: {"execute": cpu.op.code_a6, "extra_bytes": 0},
    0xa7: {"execute": cpu.op.code_a7, "extra_bytes": 0},
    0xa8: {"execute": cpu.op.code_a8, "extra_bytes": 0},
    0xa9: {"execute": cpu.op.code_a9, "extra_bytes": 0},
    0xaa: {"execute": cpu.op.code_aa, "extra_bytes": 0},
    0xab: {"execute": cpu.op.code_ab, "extra_bytes": 0},
    0xac: {"execute": cpu.op.code_ac, "extra_bytes": 0},
    0xad: {"execute": cpu.op.code_ad, "extra_bytes": 0},
    0xae: {"execute": cpu.op.code_ae, "extra_bytes": 0},
    0xaf: {"execute": cpu.op.code_af, "extra_bytes": 0},

    0xb0: {"execute": cpu.op.code_b0, "extra_bytes": 0},
    0xb1: {"execute": cpu.op.code_b1, "extra_bytes": 0},
    0xb2: {"execute": cpu.op.code_b2, "extra_bytes": 0},
    0xb3: {"execute": cpu.op.code_b3, "extra_bytes": 0},
    0xb4: {"execute": cpu.op.code_b4, "extra_bytes": 0},
    0xb5: {"execute": cpu.op.code_b5, "extra_bytes": 0},
    0xb6: {"execute": cpu.op.code_b6, "extra_bytes": 0},
    0xb7: {"execute": cpu.op.code_b7, "extra_bytes": 0},
    0xb8: {"execute": cpu.op.code_b8, "extra_bytes": 0},
    0xb9: {"execute": cpu.op.code_b9, "extra_bytes": 0},
    0xba: {"execute": cpu.op.code_ba, "extra_bytes": 0},
    0xbb: {"execute": cpu.op.code_bb, "extra_bytes": 0},
    0xbc: {"execute": cpu.op.code_bc, "extra_bytes": 0},
    0xbd: {"execute": cpu.op.code_bd, "extra_bytes": 0},
    0xbe: {"execute": cpu.op.code_be, "extra_bytes": 0},
    0xbf: {"execute": cpu.op.code_bf, "extra_bytes": 0},

    0xc0: {"execute": cpu.op.code_c0, "extra_bytes": 0},
    0xc1: {"execute": cpu.op.code_c1, "extra_bytes": 0},
    0xc2: {"execute": cpu.op.code_c2, "extra_bytes": 2},
    0xc3: {"execute": cpu.op.code_c3, "extra_bytes": 2},
    0xc4: {"execute": cpu.op.code_c4, "extra_bytes": 2},
    0xc5: {"execute": cpu.op.code_c5, "extra_bytes": 0},
    0xc6: {"execute": cpu.op.code_c6, "extra_bytes": 1},
    0xc7: {"execute": cpu.op.code_c7, "extra_bytes": 0},
    0xc8: {"execute": cpu.op.code_c8, "extra_bytes": 0},
    0xc9: {"execute": cpu.op.code_c9, "extra_bytes": 0},
    0xca: {"execute": cpu.op.code_ca, "extra_bytes": 2},
    0xcb: {"execute": cpu.op.code_cb, "extra_bytes": 0},
    0xcc: {"execute": cpu.op.code_cc, "extra_bytes": 2},
    0xcd: {"execute": cpu.op.code_cd, "extra_bytes": 2},
    0xce: {"execute": cpu.op.code_ce, "extra_bytes": 1},
    0xcf: {"execute": cpu.op.code_cf, "extra_bytes": 0},

    0xd0: {"execute": cpu.op.code_d0, "extra_bytes": 0},
    0xd1: {"execute": cpu.op.code_d1, "extra_bytes": 0},
    0xd2: {"execute": cpu.op.code_d2, "extra_bytes": 2},
    0xd3: {"execute": cpu.op.code_d3, "extra_bytes": 0},
    0xd4: {"execute": cpu.op.code_d4, "extra_bytes": 2},
    0xd5: {"execute": cpu.op.code_d5, "extra_bytes": 0},
    0xd6: {"execute": cpu.op.code_d6, "extra_bytes": 1},
    0xd7: {"execute": cpu.op.code_d7, "extra_bytes": 0},
    0xd8: {"execute": cpu.op.code_d8, "extra_bytes": 0},
    0xd9: {"execute": cpu.op.code_d9, "extra_bytes": 0},
    0xda: {"execute": cpu.op.code_da, "extra_bytes": 2},
    0xdb: {"execute": cpu.op.code_db, "extra_bytes": 0},
    0xdc: {"execute": cpu.op.code_dc, "extra_bytes": 2},
    0xdd: {"execute": cpu.op.code_dd, "extra_bytes": 0},
    0xde: {"execute": cpu.op.code_de, "extra_bytes": 1},
    0xdf: {"execute": cpu.op.code_df, "extra_bytes": 0},

    0xe0: {"execute": cpu.op.code_e0, "extra_bytes": 1},
    0xe1: {"execute": cpu.op.code_e1, "extra_bytes": 0},
    0xe2: {"execute": cpu.op.code_e2, "extra_bytes": 1},
    0xe3: {"execute": cpu.op.code_e3, "extra_bytes": 0},
    0xe4: {"execute": cpu.op.code_e4, "extra_bytes": 0},
    0xe5: {"execute": cpu.op.code_e5, "extra_bytes": 0},
    0xe6: {"execute": cpu.op.code_e6, "extra_bytes": 1},
    0xe7: {"execute": cpu.op.code_e7, "extra_bytes": 0},
    0xe8: {"execute": cpu.op.code_e8, "extra_bytes": 1},
    0xe9: {"execute": cpu.op.code_e9, "extra_bytes": 0},
    0xea: {"execute": cpu.op.code_ea, "extra_bytes": 2},
    0xeb: {"execute": cpu.op.code_eb, "extra_bytes": 0},
    0xec: {"execute": cpu.op.code_ec, "extra_bytes": 0},
    0xed: {"execute": cpu.op.code_ed, "extra_bytes": 0},
    0xee: {"execute": cpu.op.code_ee, "extra_bytes": 1},
    0xef: {"execute": cpu.op.code_ef, "extra_bytes": 0},

    0xf0: {"execute": cpu.op.code_f0, "extra_bytes": 1},
    0xf1: {"execute": cpu.op.code_f1, "extra_bytes": 0},
    0xf2: {"execute": cpu.op.code_f2, "extra_bytes": 1},
    0xf3: {"execute": cpu.op.code_f3, "extra_bytes": 0},
    0xf4: {"execute": cpu.op.code_f4, "extra_bytes": 0},
    0xf5: {"execute": cpu.op.code_f5, "extra_bytes": 0},
    0xf6: {"execute": cpu.op.code_f6, "extra_bytes": 1},
    0xf7: {"execute": cpu.op.code_f7, "extra_bytes": 0},
    0xf8: {"execute": cpu.op.code_f8, "extra_bytes": 1},
    0xf9: {"execute": cpu.op.code_f9, "extra_bytes": 0},
    0xfa: {"execute": cpu.op.code_fa, "extra_bytes": 2},
    0xfb: {"execute": cpu.op.code_fb, "extra_bytes": 0},
    0xfc: {"execute": cpu.op.code_fc, "extra_bytes": 0},
    0xfd: {"execute": cpu.op.code_fd, "extra_bytes": 0},
    0xfe: {"execute": cpu.op.code_fe, "extra_bytes": 1},
    0xff: {"execute": cpu.op.code_ff, "extra_bytes": 0}
}

_instruction_cb_dict = {
    0x00: {"execute": cpu.op.code_cb_00, "extra_bytes": 0},
    0x01: {"execute": cpu.op.code_cb_01, "extra_bytes": 0},
    0x02: {"execute": cpu.op.code_cb_02, "extra_bytes": 0},
    0x03: {"execute": cpu.op.code_cb_03, "extra_bytes": 0},
    0x04: {"execute": cpu.op.code_cb_04, "extra_bytes": 0},
    0x05: {"execute": cpu.op.code_cb_05, "extra_bytes": 0},
    0x06: {"execute": cpu.op.code_cb_06, "extra_bytes": 0},
    0x07: {"execute": cpu.op.code_cb_07, "extra_bytes": 0},
    0x08: {"execute": cpu.op.code_cb_08, "extra_bytes": 0},
    0x09: {"execute": cpu.op.code_cb_09, "extra_bytes": 0},
    0x0a: {"execute": cpu.op.code_cb_0a, "extra_bytes": 0},
    0x0b: {"execute": cpu.op.code_cb_0b, "extra_bytes": 0},
    0x0c: {"execute": cpu.op.code_cb_0c, "extra_bytes": 0},
    0x0d: {"execute": cpu.op.code_cb_0d, "extra_bytes": 0},
    0x0e: {"execute": cpu.op.code_cb_0e, "extra_bytes": 0},
    0x0f: {"execute": cpu.op.code_cb_0f, "extra_bytes": 0},

    0x10: {"execute": cpu.op.code_cb_10, "extra_bytes": 0},
    0x11: {"execute": cpu.op.code_cb_11, "extra_bytes": 0},
    0x12: {"execute": cpu.op.code_cb_12, "extra_bytes": 0},
    0x13: {"execute": cpu.op.code_cb_13, "extra_bytes": 0},
    0x14: {"execute": cpu.op.code_cb_14, "extra_bytes": 0},
    0x15: {"execute": cpu.op.code_cb_15, "extra_bytes": 0},
    0x16: {"execute": cpu.op.code_cb_16, "extra_bytes": 0},
    0x17: {"execute": cpu.op.code_cb_17, "extra_bytes": 0},
    0x18: {"execute": cpu.op.code_cb_18, "extra_bytes": 0},
    0x19: {"execute": cpu.op.code_cb_19, "extra_bytes": 0},
    0x1a: {"execute": cpu.op.code_cb_1a, "extra_bytes": 0},
    0x1b: {"execute": cpu.op.code_cb_1b, "extra_bytes": 0},
    0x1c: {"execute": cpu.op.code_cb_1c, "extra_bytes": 0},
    0x1d: {"execute": cpu.op.code_cb_1d, "extra_bytes": 0},
    0x1e: {"execute": cpu.op.code_cb_1e, "extra_bytes": 0},
    0x1f: {"execute": cpu.op.code_cb_1f, "extra_bytes": 0},

    0x20: {"execute": cpu.op.code_cb_20, "extra_bytes": 0},
    0x21: {"execute": cpu.op.code_cb_21, "extra_bytes": 0},
    0x22: {"execute": cpu.op.code_cb_22, "extra_bytes": 0},
    0x23: {"execute": cpu.op.code_cb_23, "extra_bytes": 0},
    0x24: {"execute": cpu.op.code_cb_24, "extra_bytes": 0},
    0x25: {"execute": cpu.op.code_cb_25, "extra_bytes": 0},
    0x26: {"execute": cpu.op.code_cb_26, "extra_bytes": 0},
    0x27: {"execute": cpu.op.code_cb_27, "extra_bytes": 0},
    0x28: {"execute": cpu.op.code_cb_28, "extra_bytes": 0},
    0x29: {"execute": cpu.op.code_cb_29, "extra_bytes": 0},
    0x2a: {"execute": cpu.op.code_cb_2a, "extra_bytes": 0},
    0x2b: {"execute": cpu.op.code_cb_2b, "extra_bytes": 0},
    0x2c: {"execute": cpu.op.code_cb_2c, "extra_bytes": 0},
    0x2d: {"execute": cpu.op.code_cb_2d, "extra_bytes": 0},
    0x2e: {"execute": cpu.op.code_cb_2e, "extra_bytes": 0},
    0x2f: {"execute": cpu.op.code_cb_2f, "extra_bytes": 0},

    0x30: {"execute": cpu.op.code_cb_30, "extra_bytes": 0},
    0x31: {"execute": cpu.op.code_cb_31, "extra_bytes": 0},
    0x32: {"execute": cpu.op.code_cb_32, "extra_bytes": 0},
    0x33: {"execute": cpu.op.code_cb_33, "extra_bytes": 0},
    0x34: {"execute": cpu.op.code_cb_34, "extra_bytes": 0},
    0x35: {"execute": cpu.op.code_cb_35, "extra_bytes": 0},
    0x36: {"execute": cpu.op.code_cb_36, "extra_bytes": 0},
    0x37: {"execute": cpu.op.code_cb_37, "extra_bytes": 0},
    0x38: {"execute": cpu.op.code_cb_38, "extra_bytes": 0},
    0x39: {"execute": cpu.op.code_cb_39, "extra_bytes": 0},
    0x3a: {"execute": cpu.op.code_cb_3a, "extra_bytes": 0},
    0x3b: {"execute": cpu.op.code_cb_3b, "extra_bytes": 0},
    0x3c: {"execute": cpu.op.code_cb_3c, "extra_bytes": 0},
    0x3d: {"execute": cpu.op.code_cb_3d, "extra_bytes": 0},
    0x3e: {"execute": cpu.op.code_cb_3e, "extra_bytes": 0},
    0x3f: {"execute": cpu.op.code_cb_3f, "extra_bytes": 0},

    0x40: {"execute": cpu.op.code_cb_40, "extra_bytes": 0},
    0x41: {"execute": cpu.op.code_cb_41, "extra_bytes": 0},
    0x42: {"execute": cpu.op.code_cb_42, "extra_bytes": 0},
    0x43: {"execute": cpu.op.code_cb_43, "extra_bytes": 0},
    0x44: {"execute": cpu.op.code_cb_44, "extra_bytes": 0},
    0x45: {"execute": cpu.op.code_cb_45, "extra_bytes": 0},
    0x46: {"execute": cpu.op.code_cb_46, "extra_bytes": 0},
    0x47: {"execute": cpu.op.code_cb_47, "extra_bytes": 0},
    0x48: {"execute": cpu.op.code_cb_48, "extra_bytes": 0},
    0x49: {"execute": cpu.op.code_cb_49, "extra_bytes": 0},
    0x4a: {"execute": cpu.op.code_cb_4a, "extra_bytes": 0},
    0x4b: {"execute": cpu.op.code_cb_4b, "extra_bytes": 0},
    0x4c: {"execute": cpu.op.code_cb_4c, "extra_bytes": 0},
    0x4d: {"execute": cpu.op.code_cb_4d, "extra_bytes": 0},
    0x4e: {"execute": cpu.op.code_cb_4e, "extra_bytes": 0},
    0x4f: {"execute": cpu.op.code_cb_4f, "extra_bytes": 0},

    0x50: {"execute": cpu.op.code_cb_50, "extra_bytes": 0},
    0x51: {"execute": cpu.op.code_cb_51, "extra_bytes": 0},
    0x52: {"execute": cpu.op.code_cb_52, "extra_bytes": 0},
    0x53: {"execute": cpu.op.code_cb_53, "extra_bytes": 0},
    0x54: {"execute": cpu.op.code_cb_54, "extra_bytes": 0},
    0x55: {"execute": cpu.op.code_cb_55, "extra_bytes": 0},
    0x56: {"execute": cpu.op.code_cb_56, "extra_bytes": 0},
    0x57: {"execute": cpu.op.code_cb_57, "extra_bytes": 0},
    0x58: {"execute": cpu.op.code_cb_58, "extra_bytes": 0},
    0x59: {"execute": cpu.op.code_cb_59, "extra_bytes": 0},
    0x5a: {"execute": cpu.op.code_cb_5a, "extra_bytes": 0},
    0x5b: {"execute": cpu.op.code_cb_5b, "extra_bytes": 0},
    0x5c: {"execute": cpu.op.code_cb_5c, "extra_bytes": 0},
    0x5d: {"execute": cpu.op.code_cb_5d, "extra_bytes": 0},
    0x5e: {"execute": cpu.op.code_cb_5e, "extra_bytes": 0},
    0x5f: {"execute": cpu.op.code_cb_5f, "extra_bytes": 0},

    0x60: {"execute": cpu.op.code_cb_60, "extra_bytes": 0},
    0x61: {"execute": cpu.op.code_cb_61, "extra_bytes": 0},
    0x62: {"execute": cpu.op.code_cb_62, "extra_bytes": 0},
    0x63: {"execute": cpu.op.code_cb_63, "extra_bytes": 0},
    0x64: {"execute": cpu.op.code_cb_64, "extra_bytes": 0},
    0x65: {"execute": cpu.op.code_cb_65, "extra_bytes": 0},
    0x66: {"execute": cpu.op.code_cb_66, "extra_bytes": 0},
    0x67: {"execute": cpu.op.code_cb_67, "extra_bytes": 0},
    0x68: {"execute": cpu.op.code_cb_68, "extra_bytes": 0},
    0x69: {"execute": cpu.op.code_cb_69, "extra_bytes": 0},
    0x6a: {"execute": cpu.op.code_cb_6a, "extra_bytes": 0},
    0x6b: {"execute": cpu.op.code_cb_6b, "extra_bytes": 0},
    0x6c: {"execute": cpu.op.code_cb_6c, "extra_bytes": 0},
    0x6d: {"execute": cpu.op.code_cb_6d, "extra_bytes": 0},
    0x6e: {"execute": cpu.op.code_cb_6e, "extra_bytes": 0},
    0x6f: {"execute": cpu.op.code_cb_6f, "extra_bytes": 0},

    0x70: {"execute": cpu.op.code_cb_70, "extra_bytes": 0},
    0x71: {"execute": cpu.op.code_cb_71, "extra_bytes": 0},
    0x72: {"execute": cpu.op.code_cb_72, "extra_bytes": 0},
    0x73: {"execute": cpu.op.code_cb_73, "extra_bytes": 0},
    0x74: {"execute": cpu.op.code_cb_74, "extra_bytes": 0},
    0x75: {"execute": cpu.op.code_cb_75, "extra_bytes": 0},
    0x76: {"execute": cpu.op.code_cb_76, "extra_bytes": 0},
    0x77: {"execute": cpu.op.code_cb_77, "extra_bytes": 0},
    0x78: {"execute": cpu.op.code_cb_78, "extra_bytes": 0},
    0x79: {"execute": cpu.op.code_cb_79, "extra_bytes": 0},
    0x7a: {"execute": cpu.op.code_cb_7a, "extra_bytes": 0},
    0x7b: {"execute": cpu.op.code_cb_7b, "extra_bytes": 0},
    0x7c: {"execute": cpu.op.code_cb_7c, "extra_bytes": 0},
    0x7d: {"execute": cpu.op.code_cb_7d, "extra_bytes": 0},
    0x7e: {"execute": cpu.op.code_cb_7e, "extra_bytes": 0},
    0x7f: {"execute": cpu.op.code_cb_7f, "extra_bytes": 0},

    0x80: {"execute": cpu.op.code_cb_80, "extra_bytes": 0},
    0x81: {"execute": cpu.op.code_cb_81, "extra_bytes": 0},
    0x82: {"execute": cpu.op.code_cb_82, "extra_bytes": 0},
    0x83: {"execute": cpu.op.code_cb_83, "extra_bytes": 0},
    0x84: {"execute": cpu.op.code_cb_84, "extra_bytes": 0},
    0x85: {"execute": cpu.op.code_cb_85, "extra_bytes": 0},
    0x86: {"execute": cpu.op.code_cb_86, "extra_bytes": 0},
    0x87: {"execute": cpu.op.code_cb_87, "extra_bytes": 0},
    0x88: {"execute": cpu.op.code_cb_88, "extra_bytes": 0},
    0x89: {"execute": cpu.op.code_cb_89, "extra_bytes": 0},
    0x8a: {"execute": cpu.op.code_cb_8a, "extra_bytes": 0},
    0x8b: {"execute": cpu.op.code_cb_8b, "extra_bytes": 0},
    0x8c: {"execute": cpu.op.code_cb_8c, "extra_bytes": 0},
    0x8d: {"execute": cpu.op.code_cb_8d, "extra_bytes": 0},
    0x8e: {"execute": cpu.op.code_cb_8e, "extra_bytes": 0},
    0x8f: {"execute": cpu.op.code_cb_8f, "extra_bytes": 0},

    0x90: {"execute": cpu.op.code_cb_90, "extra_bytes": 0},
    0x91: {"execute": cpu.op.code_cb_91, "extra_bytes": 0},
    0x92: {"execute": cpu.op.code_cb_92, "extra_bytes": 0},
    0x93: {"execute": cpu.op.code_cb_93, "extra_bytes": 0},
    0x94: {"execute": cpu.op.code_cb_94, "extra_bytes": 0},
    0x95: {"execute": cpu.op.code_cb_95, "extra_bytes": 0},
    0x96: {"execute": cpu.op.code_cb_96, "extra_bytes": 0},
    0x97: {"execute": cpu.op.code_cb_97, "extra_bytes": 0},
    0x98: {"execute": cpu.op.code_cb_98, "extra_bytes": 0},
    0x99: {"execute": cpu.op.code_cb_99, "extra_bytes": 0},
    0x9a: {"execute": cpu.op.code_cb_9a, "extra_bytes": 0},
    0x9b: {"execute": cpu.op.code_cb_9b, "extra_bytes": 0},
    0x9c: {"execute": cpu.op.code_cb_9c, "extra_bytes": 0},
    0x9d: {"execute": cpu.op.code_cb_9d, "extra_bytes": 0},
    0x9e: {"execute": cpu.op.code_cb_9e, "extra_bytes": 0},
    0x9f: {"execute": cpu.op.code_cb_9f, "extra_bytes": 0},

    0xa0: {"execute": cpu.op.code_cb_a0, "extra_bytes": 0},
    0xa1: {"execute": cpu.op.code_cb_a1, "extra_bytes": 0},
    0xa2: {"execute": cpu.op.code_cb_a2, "extra_bytes": 0},
    0xa3: {"execute": cpu.op.code_cb_a3, "extra_bytes": 0},
    0xa4: {"execute": cpu.op.code_cb_a4, "extra_bytes": 0},
    0xa5: {"execute": cpu.op.code_cb_a5, "extra_bytes": 0},
    0xa6: {"execute": cpu.op.code_cb_a6, "extra_bytes": 0},
    0xa7: {"execute": cpu.op.code_cb_a7, "extra_bytes": 0},
    0xa8: {"execute": cpu.op.code_cb_a8, "extra_bytes": 0},
    0xa9: {"execute": cpu.op.code_cb_a9, "extra_bytes": 0},
    0xaa: {"execute": cpu.op.code_cb_aa, "extra_bytes": 0},
    0xab: {"execute": cpu.op.code_cb_ab, "extra_bytes": 0},
    0xac: {"execute": cpu.op.code_cb_ac, "extra_bytes": 0},
    0xad: {"execute": cpu.op.code_cb_ad, "extra_bytes": 0},
    0xae: {"execute": cpu.op.code_cb_ae, "extra_bytes": 0},
    0xaf: {"execute": cpu.op.code_cb_af, "extra_bytes": 0},

    0xb0: {"execute": cpu.op.code_cb_b0, "extra_bytes": 0},
    0xb1: {"execute": cpu.op.code_cb_b1, "extra_bytes": 0},
    0xb2: {"execute": cpu.op.code_cb_b2, "extra_bytes": 0},
    0xb3: {"execute": cpu.op.code_cb_b3, "extra_bytes": 0},
    0xb4: {"execute": cpu.op.code_cb_b4, "extra_bytes": 0},
    0xb5: {"execute": cpu.op.code_cb_b5, "extra_bytes": 0},
    0xb6: {"execute": cpu.op.code_cb_b6, "extra_bytes": 0},
    0xb7: {"execute": cpu.op.code_cb_b7, "extra_bytes": 0},
    0xb8: {"execute": cpu.op.code_cb_b8, "extra_bytes": 0},
    0xb9: {"execute": cpu.op.code_cb_b9, "extra_bytes": 0},
    0xba: {"execute": cpu.op.code_cb_ba, "extra_bytes": 0},
    0xbb: {"execute": cpu.op.code_cb_bb, "extra_bytes": 0},
    0xbc: {"execute": cpu.op.code_cb_bc, "extra_bytes": 0},
    0xbd: {"execute": cpu.op.code_cb_bd, "extra_bytes": 0},
    0xbe: {"execute": cpu.op.code_cb_be, "extra_bytes": 0},
    0xbf: {"execute": cpu.op.code_cb_bf, "extra_bytes": 0},

    0xc0: {"execute": cpu.op.code_cb_c0, "extra_bytes": 0},
    0xc1: {"execute": cpu.op.code_cb_c1, "extra_bytes": 0},
    0xc2: {"execute": cpu.op.code_cb_c2, "extra_bytes": 0},
    0xc3: {"execute": cpu.op.code_cb_c3, "extra_bytes": 0},
    0xc4: {"execute": cpu.op.code_cb_c4, "extra_bytes": 0},
    0xc5: {"execute": cpu.op.code_cb_c5, "extra_bytes": 0},
    0xc6: {"execute": cpu.op.code_cb_c6, "extra_bytes": 0},
    0xc7: {"execute": cpu.op.code_cb_c7, "extra_bytes": 0},
    0xc8: {"execute": cpu.op.code_cb_c8, "extra_bytes": 0},
    0xc9: {"execute": cpu.op.code_cb_c9, "extra_bytes": 0},
    0xca: {"execute": cpu.op.code_cb_ca, "extra_bytes": 0},
    0xcb: {"execute": cpu.op.code_cb_cb, "extra_bytes": 0},
    0xcc: {"execute": cpu.op.code_cb_cc, "extra_bytes": 0},
    0xcd: {"execute": cpu.op.code_cb_cd, "extra_bytes": 0},
    0xce: {"execute": cpu.op.code_cb_ce, "extra_bytes": 0},
    0xcf: {"execute": cpu.op.code_cb_cf, "extra_bytes": 0},

    0xd0: {"execute": cpu.op.code_cb_d0, "extra_bytes": 0},
    0xd1: {"execute": cpu.op.code_cb_d1, "extra_bytes": 0},
    0xd2: {"execute": cpu.op.code_cb_d2, "extra_bytes": 0},
    0xd3: {"execute": cpu.op.code_cb_d3, "extra_bytes": 0},
    0xd4: {"execute": cpu.op.code_cb_d4, "extra_bytes": 0},
    0xd5: {"execute": cpu.op.code_cb_d5, "extra_bytes": 0},
    0xd6: {"execute": cpu.op.code_cb_d6, "extra_bytes": 0},
    0xd7: {"execute": cpu.op.code_cb_d7, "extra_bytes": 0},
    0xd8: {"execute": cpu.op.code_cb_d8, "extra_bytes": 0},
    0xd9: {"execute": cpu.op.code_cb_d9, "extra_bytes": 0},
    0xda: {"execute": cpu.op.code_cb_da, "extra_bytes": 0},
    0xdb: {"execute": cpu.op.code_cb_db, "extra_bytes": 0},
    0xdc: {"execute": cpu.op.code_cb_dc, "extra_bytes": 0},
    0xdd: {"execute": cpu.op.code_cb_dd, "extra_bytes": 0},
    0xde: {"execute": cpu.op.code_cb_de, "extra_bytes": 0},
    0xdf: {"execute": cpu.op.code_cb_df, "extra_bytes": 0},

    0xe0: {"execute": cpu.op.code_cb_e0, "extra_bytes": 0},
    0xe1: {"execute": cpu.op.code_cb_e1, "extra_bytes": 0},
    0xe2: {"execute": cpu.op.code_cb_e2, "extra_bytes": 0},
    0xe3: {"execute": cpu.op.code_cb_e3, "extra_bytes": 0},
    0xe4: {"execute": cpu.op.code_cb_e4, "extra_bytes": 0},
    0xe5: {"execute": cpu.op.code_cb_e5, "extra_bytes": 0},
    0xe6: {"execute": cpu.op.code_cb_e6, "extra_bytes": 0},
    0xe7: {"execute": cpu.op.code_cb_e7, "extra_bytes": 0},
    0xe8: {"execute": cpu.op.code_cb_e8, "extra_bytes": 0},
    0xe9: {"execute": cpu.op.code_cb_e9, "extra_bytes": 0},
    0xea: {"execute": cpu.op.code_cb_ea, "extra_bytes": 0},
    0xeb: {"execute": cpu.op.code_cb_eb, "extra_bytes": 0},
    0xec: {"execute": cpu.op.code_cb_ec, "extra_bytes": 0},
    0xed: {"execute": cpu.op.code_cb_ed, "extra_bytes": 0},
    0xee: {"execute": cpu.op.code_cb_ee, "extra_bytes": 0},
    0xef: {"execute": cpu.op.code_cb_ef, "extra_bytes": 0},

    0xf0: {"execute": cpu.op.code_cb_f0, "extra_bytes": 0},
    0xf1: {"execute": cpu.op.code_cb_f1, "extra_bytes": 0},
    0xf2: {"execute": cpu.op.code_cb_f2, "extra_bytes": 0},
    0xf3: {"execute": cpu.op.code_cb_f3, "extra_bytes": 0},
    0xf4: {"execute": cpu.op.code_cb_f4, "extra_bytes": 0},
    0xf5: {"execute": cpu.op.code_cb_f5, "extra_bytes": 0},
    0xf6: {"execute": cpu.op.code_cb_f6, "extra_bytes": 0},
    0xf7: {"execute": cpu.op.code_cb_f7, "extra_bytes": 0},
    0xf8: {"execute": cpu.op.code_cb_f8, "extra_bytes": 0},
    0xf9: {"execute": cpu.op.code_cb_f9, "extra_bytes": 0},
    0xfa: {"execute": cpu.op.code_cb_fa, "extra_bytes": 0},
    0xfb: {"execute": cpu.op.code_cb_fb, "extra_bytes": 0},
    0xfc: {"execute": cpu.op.code_cb_fc, "extra_bytes": 0},
    0xfd: {"execute": cpu.op.code_cb_fd, "extra_bytes": 0},
    0xfe: {"execute": cpu.op.code_cb_fe, "extra_bytes": 0},
    0xff: {"execute": cpu.op.code_cb_ff, "extra_bytes": 0}
}

if __name__ == '__main__':
    cpu = CPU()
